# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeffrey H. Bell
email: jeff@jhbell.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website. Stuff I find interesting and hope that maybe
  you will too. Stuff I have done and stuff I am working on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jeffreyhbell 
github_username:  jhbell 

# Build settings
markdown: kramdown
